# Generated by Django 4.2 on 2025-10-05 00:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product_qr", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productqr",
            name="product_data",
            field=models.JSONField(default=dict),
        ),
    ]
